INSERT INTO categorias(uid, descricao, url_imagem) VALUES(21520233,'Hoteis','https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80');
INSERT INTO categorias(uid, descricao, url_imagem) VALUES(21520234,'Resorts','https://images.unsplash.com/photo-1557034362-d9b6856e4cab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODB8fHJlc29ydHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60');
INSERT INTO categorias(uid, descricao, url_imagem) VALUES(21520235,'Pousadas','https://images.unsplash.com/photo-1520260022311-3babdaa7d71e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjg0fHxyZXNvcnR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60');
INSERT INTO categorias(uid, descricao, url_imagem) VALUES(21520236,'Hostels','https://images.unsplash.com/photo-1555854877-bab0e564b8d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aG9zdGVsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60');

INSERT INTO caracteristicas(uid, nome ,icone) VALUES(1234561, 'Cozinha', 'faKitchenSet');
INSERT INTO caracteristicas(uid, nome ,icone) VALUES(1234562, 'Televisão', 'faTv');
INSERT INTO caracteristicas(uid, nome ,icone) VALUES(1234563, 'Ar Condicionado', 'faSnowflake');
INSERT INTO caracteristicas(uid, nome ,icone) VALUES(1234564, 'Aceita Pets', 'faPaw');
INSERT INTO caracteristicas(uid, nome ,icone) VALUES(1234565, 'Estacionamento', 'faCar');
INSERT INTO caracteristicas(uid, nome ,icone) VALUES(1234566, 'Piscina', 'faPersonSwimming');
INSERT INTO caracteristicas(uid, nome ,icone) VALUES(1234567, 'Wifi', 'faWifi');

INSERT INTO cidades(uid, nome, pais) VALUES(30520231,'Ilhéus','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520232,'Salvador','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520233,'São Paulo','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520234,'Rio de Janeiro','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520235,'Recife','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520236,'Brasília','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520237,'Fortaleza','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520238,'Porto Alegre','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520239,'Belo Horizonte','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520240,'Foz do Iguaçu','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520241,'Gramado','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520242,'Natal','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520243,'Manaus','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520244,'Curitiba','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520245,'Pipa','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520246,'Maragogi','Brasil');
INSERT INTO cidades(uid, nome, pais) VALUES(30520247,'São Luís','Brasil');

INSERT INTO imagens(uid, titulo, url) VALUES (2305222253541,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/1_Cana_brava_ilheus/cana-brava1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253542,'Aereo','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/1_Cana_brava_ilheus/cana-brava2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253543,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/1_Cana_brava_ilheus/cana-brava3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253544,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/1_Cana_brava_ilheus/cana-brava4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253545,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/1_Cana_brava_ilheus/cana-brava5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253546,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/2_Rio_Othon_Palace/rio-othon1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253547,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/2_Rio_Othon_Palace/rio-othon2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253548,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/2_Rio_Othon_Palace/rio-othon3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253549,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/2_Rio_Othon_Palace/rio-othon4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253550,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/2_Rio_Othon_Palace/rio-othon5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253551,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/3_You_Stay_at_Vila_Olimpia/sp-you-stay1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253552,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/3_You_Stay_at_Vila_Olimpia/sp-you-stay2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253553,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/3_You_Stay_at_Vila_Olimpia/sp-you-stay3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253554,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/3_You_Stay_at_Vila_Olimpia/sp-you-stay4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253555,'Aereo','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/3_You_Stay_at_Vila_Olimpia/sp-you-stay5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253556,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/4_Bugan_Recife_Boa_Viagem_Hotel/bugan_recife1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253557,'Passaporte','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/4_Bugan_Recife_Boa_Viagem_Hotel/bugan_recife2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253558,'Aereo','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/4_Bugan_Recife_Boa_Viagem_Hotel/bugan_recife3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253559,'Trilha','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/4_Bugan_Recife_Boa_Viagem_Hotel/bugan_recife4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253560,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/4_Bugan_Recife_Boa_Viagem_Hotel/bugan_recife5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253561,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/5_ibis_Styles_Moinhos_de_Vento/ibis_porto_alegre1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253562,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/5_ibis_Styles_Moinhos_de_Vento/ibis_porto_alegre2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253563,'Breakfast','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/5_ibis_Styles_Moinhos_de_Vento/ibis_porto_alegre3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253564,'Dinner','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/5_ibis_Styles_Moinhos_de_Vento/ibis_porto_alegre4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253565,'Recife','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/5_ibis_Styles_Moinhos_de_Vento/ibis_porto_alegre5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253566,'Salvador','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/6_Pousada_Tartaruga_Praia_de_Pipa/pousada_tartaruga_rn1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253567,'Resort','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/6_Pousada_Tartaruga_Praia_de_Pipa/pousada_tartaruga_rn2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253568,'Reuniao','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/6_Pousada_Tartaruga_Praia_de_Pipa/pousada_tartaruga_rn3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253569,'Natureza','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/6_Pousada_Tartaruga_Praia_de_Pipa/pousada_tartaruga_rn4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253570,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/6_Pousada_Tartaruga_Praia_de_Pipa/pousada_tartaruga_rn5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253571,'Aereo','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/7_Assel_Pousada_Botanico/Assel_pousada_curitiba1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253572,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/7_Assel_Pousada_Botanico/Assel_pousada_curitiba2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253573,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/7_Assel_Pousada_Botanico/Assel_pousada_curitiba3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253574,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/7_Assel_Pousada_Botanico/Assel_pousada_curitiba4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253575,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/7_Assel_Pousada_Botanico/Assel_pousada_curitiba5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253576,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/8_Pousada_Su%C3%ADtes_Do_Pel%C3%B4/pousada_pelourinho_salvador1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253577,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/8_Pousada_Su%C3%ADtes_Do_Pel%C3%B4/pousada_pelourinho_salvador2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253578,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/8_Pousada_Su%C3%ADtes_Do_Pel%C3%B4/pousada_pelourinho_salvador3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253579,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/8_Pousada_Su%C3%ADtes_Do_Pel%C3%B4/pousada_pelourinho_salvador4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253580,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/8_Pousada_Su%C3%ADtes_Do_Pel%C3%B4/pousada_pelourinho_salvador5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253581,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/9_Pousada_Vitoria_da_Vila/pousada_da_vila_df_1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253582,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/9_Pousada_Vitoria_da_Vila/pousada_da_vila_df_2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253583,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/9_Pousada_Vitoria_da_Vila/pousada_da_vila_df_3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253584,'Aereo','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/9_Pousada_Vitoria_da_Vila/pousada_da_vila_df_4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253585,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/9_Pousada_Vitoria_da_Vila/pousada_da_vila_df_5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253586,'Passaporte','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/10_Casa_da_Adriana_Pousada/Casa_da_Adriana_Pousada_fortal1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253587,'Aereo','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/10_Casa_da_Adriana_Pousada/Casa_da_Adriana_Pousada_fortal2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253588,'Trilha','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/10_Casa_da_Adriana_Pousada/Casa_da_Adriana_Pousada_fortal3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253589,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/10_Casa_da_Adriana_Pousada/Casa_da_Adriana_Pousada_fortal4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253590,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/10_Casa_da_Adriana_Pousada/Casa_da_Adriana_Pousada_fortal5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253591,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/11_Grand_Oca_Maragogi_All_Inclusive_Resort/Grand_Oca_Resort_maragogi1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253592,'Breakfast','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/11_Grand_Oca_Maragogi_All_Inclusive_Resort/Grand_Oca_Resort_maragogi2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253593,'Dinner','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/11_Grand_Oca_Maragogi_All_Inclusive_Resort/Grand_Oca_Resort_maragogi3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253594,'Recife','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/11_Grand_Oca_Maragogi_All_Inclusive_Resort/Grand_Oca_Resort_maragogi4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253595,'Salvador','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/11_Grand_Oca_Maragogi_All_Inclusive_Resort/Grand_Oca_Resort_maragogi5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253596,'Resort','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/12_HOTEL_RESORT_RIO_POTY/HOTEL_RESORT_ma1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253597,'Reuniao','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/12_HOTEL_RESORT_RIO_POTY/HOTEL_RESORT_ma2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253598,'Natureza','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/12_HOTEL_RESORT_RIO_POTY/HOTEL_RESORT_ma3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253599,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/12_HOTEL_RESORT_RIO_POTY/HOTEL_RESORT_ma4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253600,'Aereo','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/12_HOTEL_RESORT_RIO_POTY/HOTEL_RESORT_ma5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253601,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/13_Serhs_Natal_Grand_Hotel_%26_Resort/serhs_Hotel_%26_Resort_rn1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253602,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/13_Serhs_Natal_Grand_Hotel_%26_Resort/serhs_Hotel_%26_Resort_rn2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253603,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/13_Serhs_Natal_Grand_Hotel_%26_Resort/serhs_Hotel_%26_Resort_rn3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253604,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/13_Serhs_Natal_Grand_Hotel_%26_Resort/serhs_Hotel_%26_Resort_rn4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253605,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/13_Serhs_Natal_Grand_Hotel_%26_Resort/serhs_Hotel_%26_Resort_rn5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253606,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/14_Amaz%C3%B4nia_Golf_Resort/Golf_Resort_am1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253607,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/14_Amaz%C3%B4nia_Golf_Resort/Golf_Resort_am2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253608,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/14_Amaz%C3%B4nia_Golf_Resort/Golf_Resort_am3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253609,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/14_Amaz%C3%B4nia_Golf_Resort/Golf_Resort_am4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253610,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/14_Amaz%C3%B4nia_Golf_Resort/Golf_Resort_am5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253611,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/15_Bourbon_Thermas_Eco_Resort/eco_resort_foz1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253612,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/15_Bourbon_Thermas_Eco_Resort/eco_resort_foz2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253613,'Aereo','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/15_Bourbon_Thermas_Eco_Resort/eco_resort_foz3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253614,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/15_Bourbon_Thermas_Eco_Resort/eco_resort_foz4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253615,'Passaporte','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/15_Bourbon_Thermas_Eco_Resort/eco_resort_foz5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253616,'Aereo','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/16_Brazilodge_All_Suites_Hostel/Brazilodge_Suites_Hostel_sp1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253617,'Trilha','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/16_Brazilodge_All_Suites_Hostel/Brazilodge_Suites_Hostel_sp2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253618,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/16_Brazilodge_All_Suites_Hostel/Brazilodge_Suites_Hostel_sp3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253619,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/16_Brazilodge_All_Suites_Hostel/Brazilodge_Suites_Hostel_sp4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253620,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/16_Brazilodge_All_Suites_Hostel/Brazilodge_Suites_Hostel_sp5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253621,'Breakfast','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/17_Zili_Pernambuco_-_Hostel_Pousada/zili_hostel_pe1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253622,'Dinner','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/17_Zili_Pernambuco_-_Hostel_Pousada/zili_hostel_pe2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253623,'Recife','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/17_Zili_Pernambuco_-_Hostel_Pousada/zili_hostel_pe3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253624,'Salvador','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/17_Zili_Pernambuco_-_Hostel_Pousada/zili_hostel_pe4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253625,'Resort','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/17_Zili_Pernambuco_-_Hostel_Pousada/zili_hostel_pe5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253626,'Reuniao','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/18_Rota_BH_Hostel/rota_hostel_bh1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253627,'Natureza','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/18_Rota_BH_Hostel/rota_hostel_bh2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253628,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/18_Rota_BH_Hostel/rota_hostel_bh3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253629,'Aereo','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/18_Rota_BH_Hostel/rota_hostel_bh4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253630,'Passeio','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/18_Rota_BH_Hostel/rota_hostel_bh5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253631,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/19_Nomads_Hostel_Multicultural/nomads_hostel_ssa1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253632,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/19_Nomads_Hostel_Multicultural/nomads_hostel_ssa2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253633,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/19_Nomads_Hostel_Multicultural/nomads_hostel_ssa3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253634,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/19_Nomads_Hostel_Multicultural/nomads_hostel_ssa4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253635,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/19_Nomads_Hostel_Multicultural/nomads_hostel_ssa5.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253636,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/20_Hostel_Chocolatch%C3%AA/Hostel_Chocolatch%C3%AA_gramado1.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253637,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/20_Hostel_Chocolatch%C3%AA/Hostel_Chocolatch%C3%AA_gramado2.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253638,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/20_Hostel_Chocolatch%C3%AA/Hostel_Chocolatch%C3%AA_gramado3.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253639,'Hotel','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/20_Hostel_Chocolatch%C3%AA/Hostel_Chocolatch%C3%AA_gramado4.jpg');
INSERT INTO imagens(uid, titulo, url) VALUES (2305222253640,'Quarto','https://digitalbooking-colecao.s3.sa-east-1.amazonaws.com/Imagens+pro+banco/20_Hostel_Chocolatch%C3%AA/Hostel_Chocolatch%C3%AA_gramado5.jpg');

INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254161, 'Cana Brava Resort', 'O Cana Brava Resort é um destino completo de férias, na mais bela praia de Ilhéus, sul da Bahia. Aqui a diversão não tem hora para acabar, com atividades diárias para adultos e crianças. Além disso, nossos hóspedes aproveitam de deliciosas opções do serviço all inclusive, e realizam uma verdadeira viagem gastronômica por diferentes culinárias. Tudo isso em meio à paisagens encantadoras que irão te surpreender.', -14.994043646307352, -38.99990493168996, 5, 7, 1, 1);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254162, 'Rio Othon Palace', 'Localizado à beira-mar da praia de Copacabana, o Rio Othon Palace oferece piscina na cobertura, com uma vista excelente do Pão de Açúcar, e academia no local. O café da manhã é servido no 3º andar, com vista panorâmica do mar. Para sua comodidade, a propriedade dispõe de Wi-Fi gratuito em todas as áreas. Todas as acomodações do Rio Othon Palace incluem ar-condicionado, varanda, TV a cabo e frigobar.', -22.977230583418038, -43.18916394605217,  5, 7, 1, 4);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254163, 'You Stay at Vila Olimpia', 'Com vista da cidade, o You Stay at Vila Olimpia - ITC está localizado em São Paulo e oferece restaurante, serviço de quarto, bar, jardim, piscina ao ar livre aberta o ano todo e terraço ao ar livre. O apart-hotel oferece Wi-Fi e estacionamento privativo gratuitos. O You Stay at Vila Olimpia - ITC oferece área de estar com TV de tela plana e banheiro privativo com amenidades de banho gratuitas, secador de cabelo e chuveiro.', -23.594820142324142, -46.68789471610566, 5, 6, 1, 3);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254164, 'Bugan Recife Boa Viagem Hotel', 'Oferecendo piscina ao ar livre e academia, o Bugan Recife Hotel by Atlantica está localizado em Recife. O Wi-Fi gratuito está à sua disposição. A Praia da Boa Viagem fica a 400 metros deste hotel.', -8.128622962139861, -34.90154640406308, 4, 8, 1, 5);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254165, 'ibis Styles Moinhos de Vento', 'A propriedade fica a 8,6 km do Estádio Beira Rio, O ibis Styles Porto Alegre Moinhos de Vento oferece acomodações 3 estrelas em Porto Alegre e dispõe de um bar. Este hotel 3 estrelas dispõe de academia e quartos com ar-condicionado, Wi-Fi gratuito e banheiro privativo. A propriedade é para não fumantes e está situada a 39 km da Estação Rodoviária de Novo Hamburgo.', -30.022183711001247, -51.19353763477609, 3, 9, 1, 8);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254166, 'Pousada Tartaruga Praia de Pipa', 'A Pousada Tartaruga fica na Rua Principal, na Praia de Pipa, conhecida por suas ondas ideais para a prática de surfe. Dispõe de uma piscina ao ar livre situada em jardins floridos e palmeiras tropicais. O estacionamento e o Wi-Fi estão disponíveis gratuitamente.', -6.228030042336687, -35.05128269719976, 3, 9, 3, 15);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254167, 'Assel Pousada Botanico', 'A Assel Pousada Botanico, com WiFi gratuito em todas as áreas, está localizada a apenas 900 m do Jardim Botânico de Curitiba. Durante sua estadia na Assel Pousada Botanico, você pode utilizar a cozinha compartilhada com eletrodomésticos, utensílios e talheres. A sala de estar dispõe de varanda com vista para a cidade.', -25.441994362661497, -49.25010771521252, 3, 9, 3, 14);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254168, 'Pousada Suítes Do Pelô', 'A Pousada Suítes do Pelô está situada no centro histórico de Salvador, a apenas 20 km do Aeroporto Luís Eduardo Magalhães. A propriedade oferece acomodações básicas com WiFi gratuito.', -12.9739052348436, -38.507532193842934, 2, 8, 3, 2);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254169, 'Pousada Vitória da Vila', 'Situada em Brasília, a 3,6 km do Palácio da Justiça, a Pousada Vitória da Vila oferece lounge compartilhado, quartos para não fumantes e Wi-Fi gratuito em todas as áreas. A propriedade fica a cerca de 4,2 km do Congresso Nacional do Brasil, a 4,4 km da Praça dos Três Poderes e a 4,7 km da Catedral de Brasília. A pousada dispõe de quartos família.', -15.792285925577112, -47.846946819236585, 3, 9, 3, 6);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254170, 'Casa da Adriana Pousada', 'Situada em Fortaleza, a 2,1 km da Praia do Meireles, a Casa da Adriana Pousada oferece acomodações com jardim, estacionamento privativo gratuito e terraço. Localizada a cerca de 2,8 km da Praia de Iracema, a pousada com Wi-Fi gratuito também fica a 8,2 km do North Shopping. Todos os quartos possuem varanda.', -3.7424884494042674, -38.503574632074454, 3, 8, 3, 7);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254171, 'Grand Oca Maragogi All Inclusive Resort', 'Localizado em frente à Praia Ponta de Mangue, o Grand Oca fica a 350 metros das piscinas naturais e oferece Wi-Fi gratuito nas áreas comuns. Todos os quartos Standard incluem varanda e ar-condicionado. Os bangalôs do Grand Oca Maragogi dispõem de ar-condicionado e vista panorâmica do jardim ou da piscina.', -8.958979715392777, -35.178164703645855, 3, 9, 2, 16);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254172, 'HOTEL RESORT RIO POTY', 'Localizado em São Luís, a 1 km da Praia de São Marcos, o HOTEL RESORT RIO POTY oferece acomodações com jardim, estacionamento privativo gratuito, terraço e restaurante. Este hotel 4 estrelas dispõe de bar e quartos com ar-condicionado, Wi-Fi gratuito e banheiro privativo. A acomodação dispõe de serviço de quarto, recepção 24 horas e depósito para bagagem.', -2.4848170447506965, -44.305058662920416, 4, 9, 2, 17);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254173, 'Serhs Natal Grand Hotel & Resort', 'O Serhs Natal Grand Hotel é um resort à beira-mar localizado entre as praias de Ponta Negra e Areia Preta. Este complexo oferece 4 piscinas, 3 bares, 5 restaurantes, uma variedade de refeições e bebidas e opções de entretenimento. O Wi-Fi gratuito está à sua disposição em todas as áreas.', -5.8547100992022125, -35.181660574557, 4, 8, 2, 4);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254174, 'Amazônia Golf Resort', 'O Amazonia Golf Resort By Nobile está localizado a 59 km do Aeroporto Internacional de Manaus - Eduardo Gomes. O resort conta com internet Wi-Fi grátis e campo oficial de golfe. As acomodações estão equipadas com ar-condicionado split, TV LCD, cofre e frigobar. Os banheiros são privativos e contam com secador de cabelos.', -2.7052572229366443, -59.726012916288795, 3, 7, 2, 13);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254175, 'Bourbon Thermas Eco Resort', 'Idealmente localizado na fronteira entre Brasil, Argentina e Paraguai, este hotel resort 5 estrelas para não fumantes oferece acomodações modernas a 22 km das Cataratas do Iguaçu. O WiFi está disponível gratuitamente em toda a propriedade.', -25.5597460310984, -54.559583033925996, 5, 9, 2, 10);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254176, 'Brazilodge All Suites Hostel', 'Situado a apenas 800 m da Estação de Metrô Ana Rosa, em São Paulo, o Brazilodge All Suites tem uma cozinha de uso comum, um salão de jogos e Wi-Fi gratuito. O albergue também conta com um buffet de café-da-manhã diário e acomodações com ar-condicionado.', -23.586052633371224, -46.6436312331994, 2, 9, 4, 16);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254177, 'Zili Pernambuco - Hostel Pousada', 'Com jardim, lounge compartilhado, bar e Wi-Fi gratuito, o Zili Pernambuco - Hostel Pousada está situado em Recife, a 16 km do Shopping Guararapes e a menos de 1 km do Museu de Arte Moderna Aloísio Magalhães. A propriedade está localizada a 1,4 km da Ponte Buarque de Macedo, a 2,2 km da Ponte Giratória - Ponte 12 de Setembro e a 2,5 km do Porto de Recife. A acomodação oferece karaokê e cozinha compartilhada.', -8.056443789709505, -34.88548555961083, 2, 8, 4, 5);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254178, 'Rota BH Hostel', 'O Rota BH Hostel está localizado em Belo Horizonte, a 1,1 km da Estação Rodoviária de Belo Horizonte. Os quartos oferecem acesso a um banheiro compartilhado. O Rota BH Hostel também dispõe de Wi-Fi gratuito em todos os ambientes. O Rota BH fica a 7 km do Estádio Mineirão e a 8 km da Igreja de São Francisco de Assis. Já o Aeroporto Carlos Drummond de Andrade fica a 8 km do local.', -19.920023054435024, -43.94893065926679, 2, 8, 4, 9);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254179, 'Nomads Hostel Multicultural', 'O Nomads Hostel Multicultural & Coworking, em Salvador, oferece acomodações apenas para adultos com jardim e bar. Dispondo de terraço ao ar livre, esta propriedade está localizada a uma curta distância do Porto da Barra, da Praia do Farol da Barra e do Farol da Barra. A acomodação oferece cozinha compartilhada e Wi-Fi gratuito.', -13.002389075107768, -38.52822185722651, 2, 7, 4, 2);
INSERT INTO produtos(uid, nome, descricao, latitude, longitude,qualificacao,classificacao,categoria_id, cidade_id) VALUES(2305222254180, 'Hostel Chocolatchê', 'Convenientemente localizado em Gramado, o Hostel Chocolatchê oferece buffet de café da manhã e Wi-Fi gratuito em todas as áreas. A propriedade fica a 2,6 km do Lago Negro de Gramado, a 8,2 km da Catedral de Pedra e a 34 km do Parque do Vale do Imigrante. A acomodação oferece lounge compartilhado, serviço de concierge e organização de passeios.', -29.37700136147912, -50.87500390190019, 4, 8, 4, 11);

INSERT INTO produto_imagens VALUES (1,1);
INSERT INTO produto_imagens VALUES (1,2);
INSERT INTO produto_imagens VALUES (1,3);
INSERT INTO produto_imagens VALUES (1,4);
INSERT INTO produto_imagens VALUES (1,5);
INSERT INTO produto_imagens VALUES (2,6);
INSERT INTO produto_imagens VALUES (2,7);
INSERT INTO produto_imagens VALUES (2,8);
INSERT INTO produto_imagens VALUES (2,9);
INSERT INTO produto_imagens VALUES (2,10);
INSERT INTO produto_imagens VALUES (3,11);
INSERT INTO produto_imagens VALUES (3,12);
INSERT INTO produto_imagens VALUES (3,13);
INSERT INTO produto_imagens VALUES (3,14);
INSERT INTO produto_imagens VALUES (3,15);
INSERT INTO produto_imagens VALUES (4,16);
INSERT INTO produto_imagens VALUES (4,17);
INSERT INTO produto_imagens VALUES (4,18);
INSERT INTO produto_imagens VALUES (4,19);
INSERT INTO produto_imagens VALUES (4,20);
INSERT INTO produto_imagens VALUES (5,21);
INSERT INTO produto_imagens VALUES (5,22);
INSERT INTO produto_imagens VALUES (5,23);
INSERT INTO produto_imagens VALUES (5,24);
INSERT INTO produto_imagens VALUES (5,25);
INSERT INTO produto_imagens VALUES (6,26);
INSERT INTO produto_imagens VALUES (6,27);
INSERT INTO produto_imagens VALUES (6,28);
INSERT INTO produto_imagens VALUES (6,29);
INSERT INTO produto_imagens VALUES (6,30);
INSERT INTO produto_imagens VALUES (7,31);
INSERT INTO produto_imagens VALUES (7,32);
INSERT INTO produto_imagens VALUES (7,33);
INSERT INTO produto_imagens VALUES (7,34);
INSERT INTO produto_imagens VALUES (7,35);
INSERT INTO produto_imagens VALUES (8,36);
INSERT INTO produto_imagens VALUES (8,37);
INSERT INTO produto_imagens VALUES (8,38);
INSERT INTO produto_imagens VALUES (8,39);
INSERT INTO produto_imagens VALUES (8,40);
INSERT INTO produto_imagens VALUES (9,41);
INSERT INTO produto_imagens VALUES (9,42);
INSERT INTO produto_imagens VALUES (9,43);
INSERT INTO produto_imagens VALUES (9,44);
INSERT INTO produto_imagens VALUES (9,45);
INSERT INTO produto_imagens VALUES (10,46);
INSERT INTO produto_imagens VALUES (10,47);
INSERT INTO produto_imagens VALUES (10,48);
INSERT INTO produto_imagens VALUES (10,49);
INSERT INTO produto_imagens VALUES (10,50);
INSERT INTO produto_imagens VALUES (11,51);
INSERT INTO produto_imagens VALUES (11,52);
INSERT INTO produto_imagens VALUES (11,53);
INSERT INTO produto_imagens VALUES (11,54);
INSERT INTO produto_imagens VALUES (11,55);
INSERT INTO produto_imagens VALUES (12,56);
INSERT INTO produto_imagens VALUES (12,57);
INSERT INTO produto_imagens VALUES (12,58);
INSERT INTO produto_imagens VALUES (12,59);
INSERT INTO produto_imagens VALUES (12,60);
INSERT INTO produto_imagens VALUES (13,61);
INSERT INTO produto_imagens VALUES (13,62);
INSERT INTO produto_imagens VALUES (13,63);
INSERT INTO produto_imagens VALUES (13,64);
INSERT INTO produto_imagens VALUES (13,65);
INSERT INTO produto_imagens VALUES (14,66);
INSERT INTO produto_imagens VALUES (14,67);
INSERT INTO produto_imagens VALUES (14,68);
INSERT INTO produto_imagens VALUES (14,69);
INSERT INTO produto_imagens VALUES (14,70);
INSERT INTO produto_imagens VALUES (15,71);
INSERT INTO produto_imagens VALUES (15,72);
INSERT INTO produto_imagens VALUES (15,73);
INSERT INTO produto_imagens VALUES (15,74);
INSERT INTO produto_imagens VALUES (15,75);
INSERT INTO produto_imagens VALUES (16,76);
INSERT INTO produto_imagens VALUES (16,77);
INSERT INTO produto_imagens VALUES (16,78);
INSERT INTO produto_imagens VALUES (16,79);
INSERT INTO produto_imagens VALUES (16,80);
INSERT INTO produto_imagens VALUES (17,81);
INSERT INTO produto_imagens VALUES (17,82);
INSERT INTO produto_imagens VALUES (17,83);
INSERT INTO produto_imagens VALUES (17,84);
INSERT INTO produto_imagens VALUES (17,85);
INSERT INTO produto_imagens VALUES (18,86);
INSERT INTO produto_imagens VALUES (18,87);
INSERT INTO produto_imagens VALUES (18,88);
INSERT INTO produto_imagens VALUES (18,89);
INSERT INTO produto_imagens VALUES (18,90);
INSERT INTO produto_imagens VALUES (19,91);
INSERT INTO produto_imagens VALUES (19,92);
INSERT INTO produto_imagens VALUES (19,93);
INSERT INTO produto_imagens VALUES (19,94);
INSERT INTO produto_imagens VALUES (19,95);
INSERT INTO produto_imagens VALUES (20,96);
INSERT INTO produto_imagens VALUES (20,97);
INSERT INTO produto_imagens VALUES (20,98);
INSERT INTO produto_imagens VALUES (20,99);
INSERT INTO produto_imagens VALUES (20,100);

INSERT INTO produtos_caracteristicas VALUES (1,1);
INSERT INTO produtos_caracteristicas VALUES (1,2);
INSERT INTO produtos_caracteristicas VALUES (1,3);
INSERT INTO produtos_caracteristicas VALUES (1,4);
INSERT INTO produtos_caracteristicas VALUES (1,5);
INSERT INTO produtos_caracteristicas VALUES (1,6);
INSERT INTO produtos_caracteristicas VALUES (1,7);
INSERT INTO produtos_caracteristicas VALUES (2,1);
INSERT INTO produtos_caracteristicas VALUES (2,2);
INSERT INTO produtos_caracteristicas VALUES (2,3);
INSERT INTO produtos_caracteristicas VALUES (2,4);
INSERT INTO produtos_caracteristicas VALUES (3,3);
INSERT INTO produtos_caracteristicas VALUES (3,4);
INSERT INTO produtos_caracteristicas VALUES (3,5);
INSERT INTO produtos_caracteristicas VALUES (3,6);
INSERT INTO produtos_caracteristicas VALUES (3,7);
INSERT INTO produtos_caracteristicas VALUES (4,2);
INSERT INTO produtos_caracteristicas VALUES (4,3);
INSERT INTO produtos_caracteristicas VALUES (4,4);
INSERT INTO produtos_caracteristicas VALUES (4,5);
INSERT INTO produtos_caracteristicas VALUES (4,6);
INSERT INTO produtos_caracteristicas VALUES (4,7);
INSERT INTO produtos_caracteristicas VALUES (5,1);
INSERT INTO produtos_caracteristicas VALUES (5,3);
INSERT INTO produtos_caracteristicas VALUES (5,4);
INSERT INTO produtos_caracteristicas VALUES (5,5);
INSERT INTO produtos_caracteristicas VALUES (6,2);
INSERT INTO produtos_caracteristicas VALUES (6,3);
INSERT INTO produtos_caracteristicas VALUES (6,4);
INSERT INTO produtos_caracteristicas VALUES (6,5);
INSERT INTO produtos_caracteristicas VALUES (7,2);
INSERT INTO produtos_caracteristicas VALUES (7,3);
INSERT INTO produtos_caracteristicas VALUES (7,4);
INSERT INTO produtos_caracteristicas VALUES (7,5);
INSERT INTO produtos_caracteristicas VALUES (7,6);
INSERT INTO produtos_caracteristicas VALUES (7,7);
INSERT INTO produtos_caracteristicas VALUES (8,1);
INSERT INTO produtos_caracteristicas VALUES (8,2);
INSERT INTO produtos_caracteristicas VALUES (8,3);
INSERT INTO produtos_caracteristicas VALUES (8,4);
INSERT INTO produtos_caracteristicas VALUES (8,5);
INSERT INTO produtos_caracteristicas VALUES (8,6);
INSERT INTO produtos_caracteristicas VALUES (8,7);
INSERT INTO produtos_caracteristicas VALUES (9,1);
INSERT INTO produtos_caracteristicas VALUES (9,2);
INSERT INTO produtos_caracteristicas VALUES (9,3);
INSERT INTO produtos_caracteristicas VALUES (9,4);
INSERT INTO produtos_caracteristicas VALUES (9,5);
INSERT INTO produtos_caracteristicas VALUES (9,6);
INSERT INTO produtos_caracteristicas VALUES (9,7);
INSERT INTO produtos_caracteristicas VALUES (10,1);
INSERT INTO produtos_caracteristicas VALUES (10,2);
INSERT INTO produtos_caracteristicas VALUES (10,3);
INSERT INTO produtos_caracteristicas VALUES (10,4);
INSERT INTO produtos_caracteristicas VALUES (10,5);
INSERT INTO produtos_caracteristicas VALUES (10,6);
INSERT INTO produtos_caracteristicas VALUES (10,7);
INSERT INTO produtos_caracteristicas VALUES (11,1);
INSERT INTO produtos_caracteristicas VALUES (11,2);
INSERT INTO produtos_caracteristicas VALUES (11,3);
INSERT INTO produtos_caracteristicas VALUES (11,4);
INSERT INTO produtos_caracteristicas VALUES (11,5);
INSERT INTO produtos_caracteristicas VALUES (11,6);
INSERT INTO produtos_caracteristicas VALUES (11,7);
INSERT INTO produtos_caracteristicas VALUES (12,1);
INSERT INTO produtos_caracteristicas VALUES (12,2);
INSERT INTO produtos_caracteristicas VALUES (12,3);
INSERT INTO produtos_caracteristicas VALUES (12,4);
INSERT INTO produtos_caracteristicas VALUES (12,5);
INSERT INTO produtos_caracteristicas VALUES (12,6);
INSERT INTO produtos_caracteristicas VALUES (12,7);
INSERT INTO produtos_caracteristicas VALUES (13,1);
INSERT INTO produtos_caracteristicas VALUES (13,2);
INSERT INTO produtos_caracteristicas VALUES (13,3);
INSERT INTO produtos_caracteristicas VALUES (13,4);
INSERT INTO produtos_caracteristicas VALUES (13,5);
INSERT INTO produtos_caracteristicas VALUES (13,6);
INSERT INTO produtos_caracteristicas VALUES (13,7);
INSERT INTO produtos_caracteristicas VALUES (14,1);
INSERT INTO produtos_caracteristicas VALUES (14,2);
INSERT INTO produtos_caracteristicas VALUES (14,3);
INSERT INTO produtos_caracteristicas VALUES (14,4);
INSERT INTO produtos_caracteristicas VALUES (14,5);
INSERT INTO produtos_caracteristicas VALUES (14,6);
INSERT INTO produtos_caracteristicas VALUES (14,7);
INSERT INTO produtos_caracteristicas VALUES (15,1);
INSERT INTO produtos_caracteristicas VALUES (15,2);
INSERT INTO produtos_caracteristicas VALUES (15,3);
INSERT INTO produtos_caracteristicas VALUES (15,4);
INSERT INTO produtos_caracteristicas VALUES (15,5);
INSERT INTO produtos_caracteristicas VALUES (15,6);
INSERT INTO produtos_caracteristicas VALUES (15,7);
INSERT INTO produtos_caracteristicas VALUES (16,1);
INSERT INTO produtos_caracteristicas VALUES (16,2);
INSERT INTO produtos_caracteristicas VALUES (16,3);
INSERT INTO produtos_caracteristicas VALUES (16,4);
INSERT INTO produtos_caracteristicas VALUES (16,5);
INSERT INTO produtos_caracteristicas VALUES (16,6);
INSERT INTO produtos_caracteristicas VALUES (16,7);
INSERT INTO produtos_caracteristicas VALUES (17,1);
INSERT INTO produtos_caracteristicas VALUES (17,2);
INSERT INTO produtos_caracteristicas VALUES (17,7);
INSERT INTO produtos_caracteristicas VALUES (18,2);
INSERT INTO produtos_caracteristicas VALUES (18,7);
INSERT INTO produtos_caracteristicas VALUES (19,2);
INSERT INTO produtos_caracteristicas VALUES (19,3);
INSERT INTO produtos_caracteristicas VALUES (19,4);
INSERT INTO produtos_caracteristicas VALUES (19,7);
INSERT INTO produtos_caracteristicas VALUES (20,2);
INSERT INTO produtos_caracteristicas VALUES (20,3);
INSERT INTO produtos_caracteristicas VALUES (20,4);
INSERT INTO produtos_caracteristicas VALUES (20,7);

INSERT INTO perfis(nome) VALUES('ADMIN');
INSERT INTO perfis(nome) VALUES('USER');

INSERT INTO usuarios(email,senha , nome,sobrenome) VALUES('email@email.com','$2a$10$4vmqxz3WQwuDr1YsY/L33eBwL7z/a6IOIIQiCXmefxi8NQ9sCmRee' , 'Usuario', 'de Teste');
INSERT INTO usuarios(email,senha , nome,sobrenome) VALUES('adm@email.com','$2a$10$4vmqxz3WQwuDr1YsY/L33eBwL7z/a6IOIIQiCXmefxi8NQ9sCmRee' , 'Usuario', 'Administrador');

INSERT INTO usuarios_perfis(usuario_id, perfis_id) VALUES (1,2);
INSERT INTO usuarios_perfis(usuario_id, perfis_id) VALUES (2,1);

INSERT INTO reservas(uid, data_final_reserva, data_inicio_reserva, hora_inicio_reserva, produto_id, usuario_id) VALUES(2306132325399, '2023-06-20 10:30:00', '2023-06-14 10:30:00', '2023-06-14 12:30:00', 1, 1);
